#!/bin/bash

step "remove cache"
rm -rf ./cache

step "install dependencies"
npm install --no-optional

step "link dev tools"
ln -s "/app/tools/reload" /usr/bin/reload
ln -s "/app/tools/reload" /usr/bin/restart

step "run"
export FORCE_COLOR=1
logger next npm run dev
